---
- name: set timezone variables
  copy:
    content: |
      {{ timezone }}

    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: no
  notify:
  - dpkg-reconfigure tzdata
